# Welcome to Jekyll!
#

# Site settings
title: 逆光之地
description: |
  总想找一个地方静静地写些什么，于是就留在了这里  
  迟刚的笔记  
  生活 工作 游记 感悟  

owner: Chi Gang(Justin) # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: chigang@huawei.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/nonoazoro
  github: https://github.com/Justin-chi
  #weibo: https://weibo.com/chigang
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: chigang@huawei.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
